//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dan_LVII_Milos_Peric.ProductServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/WCFProductService")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemsRemainingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemsRemaining {
            get {
                return this.ItemsRemainingField;
            }
            set {
                if ((this.ItemsRemainingField.Equals(value) != true)) {
                    this.ItemsRemainingField = value;
                    this.RaisePropertyChanged("ItemsRemaining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceReference.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAllProducts", ReplyAction="http://tempuri.org/IProductService/GetAllProductsResponse")]
        Dan_LVII_Milos_Peric.ProductServiceReference.Product[] GetAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAllProducts", ReplyAction="http://tempuri.org/IProductService/GetAllProductsResponse")]
        System.Threading.Tasks.Task<Dan_LVII_Milos_Peric.ProductServiceReference.Product[]> GetAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/CreateReceipt", ReplyAction="http://tempuri.org/IProductService/CreateReceiptResponse")]
        void CreateReceipt(Dan_LVII_Milos_Peric.ProductServiceReference.Product[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/CreateReceipt", ReplyAction="http://tempuri.org/IProductService/CreateReceiptResponse")]
        System.Threading.Tasks.Task CreateReceiptAsync(Dan_LVII_Milos_Peric.ProductServiceReference.Product[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ModifyProductStock", ReplyAction="http://tempuri.org/IProductService/ModifyProductStockResponse")]
        void ModifyProductStock(int id, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ModifyProductStock", ReplyAction="http://tempuri.org/IProductService/ModifyProductStockResponse")]
        System.Threading.Tasks.Task ModifyProductStockAsync(int id, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/AddNewProduct", ReplyAction="http://tempuri.org/IProductService/AddNewProductResponse")]
        void AddNewProduct(Dan_LVII_Milos_Peric.ProductServiceReference.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/AddNewProduct", ReplyAction="http://tempuri.org/IProductService/AddNewProductResponse")]
        System.Threading.Tasks.Task AddNewProductAsync(Dan_LVII_Milos_Peric.ProductServiceReference.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ModifyProductPrice", ReplyAction="http://tempuri.org/IProductService/ModifyProductPriceResponse")]
        void ModifyProductPrice(int id, double price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ModifyProductPrice", ReplyAction="http://tempuri.org/IProductService/ModifyProductPriceResponse")]
        System.Threading.Tasks.Task ModifyProductPriceAsync(int id, double price);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : Dan_LVII_Milos_Peric.ProductServiceReference.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<Dan_LVII_Milos_Peric.ProductServiceReference.IProductService>, Dan_LVII_Milos_Peric.ProductServiceReference.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Dan_LVII_Milos_Peric.ProductServiceReference.Product[] GetAllProducts() {
            return base.Channel.GetAllProducts();
        }
        
        public System.Threading.Tasks.Task<Dan_LVII_Milos_Peric.ProductServiceReference.Product[]> GetAllProductsAsync() {
            return base.Channel.GetAllProductsAsync();
        }
        
        public void CreateReceipt(Dan_LVII_Milos_Peric.ProductServiceReference.Product[] list) {
            base.Channel.CreateReceipt(list);
        }
        
        public System.Threading.Tasks.Task CreateReceiptAsync(Dan_LVII_Milos_Peric.ProductServiceReference.Product[] list) {
            return base.Channel.CreateReceiptAsync(list);
        }
        
        public void ModifyProductStock(int id, int amount) {
            base.Channel.ModifyProductStock(id, amount);
        }
        
        public System.Threading.Tasks.Task ModifyProductStockAsync(int id, int amount) {
            return base.Channel.ModifyProductStockAsync(id, amount);
        }
        
        public void AddNewProduct(Dan_LVII_Milos_Peric.ProductServiceReference.Product product) {
            base.Channel.AddNewProduct(product);
        }
        
        public System.Threading.Tasks.Task AddNewProductAsync(Dan_LVII_Milos_Peric.ProductServiceReference.Product product) {
            return base.Channel.AddNewProductAsync(product);
        }
        
        public void ModifyProductPrice(int id, double price) {
            base.Channel.ModifyProductPrice(id, price);
        }
        
        public System.Threading.Tasks.Task ModifyProductPriceAsync(int id, double price) {
            return base.Channel.ModifyProductPriceAsync(id, price);
        }
    }
}
